# file: tasks/main.yml
---
- name: Create partition
  community.general.parted:
    device: "/dev/sdb"
    number: 1
    label: gpt
    state: present
    part_type: primary
    part_start: 0%
    part_end: 100%

- name: Create filesystem
  community.general.filesystem:
    dev: "/dev/sdb1"
    fstype: ext4
    resizefs: true

- name: Create mount point
  ansible.builtin.file:
    path: "/mnt/data"
    state: directory
    owner: root
    group: root
    mode: 0777

- name: Mount disk
  ansible.builtin.mount:
    path: "/mnt/data"
    src: "/dev/sdb1"
    fstype: ext4
    state: mounted

- name: Add mount point to fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "/dev/sdb1 /mnt/data ext4 defaults 0 0"
